const products = [
    {
        id: 1,
        name: "iPhone 12 Pro",
        brand: "Apple",
        desc: "6.1-inch display",
        price: 75000,
        image: "https://res.cloudinary.com/din4z2w7i/image/upload/v1711523674/online-shop/galaxyS_assruw.png",
    },
    {
        id: 2,
        name: "iPhone 12",
        brand: "Apple",
        desc: "5.4-inch mini display",
        price: 53000,
        image: "https://res.cloudinary.com/din4z2w7i/image/upload/v1711523674/online-shop/iphone12_mnusgn.jpg",
    },
    {
        id: 3,
        name: "Galaxy S",
        brand: "Samsung",
        desc: "6.5-inch display",
        price: 35000,
        image: "https://res.cloudinary.com/din4z2w7i/image/upload/v1711523674/online-shop/iphone12pro_k2kfnk.jpg",
    },
    {
        id: 4,
        name: "iPhone 12 Pro",
        brand: "Apple",
        desc: "6.1-inch display",
        price: 75000,
        image: "https://res.cloudinary.com/din4z2w7i/image/upload/v1711523674/online-shop/galaxyS_assruw.png",
    },
    {
        id: 5,
        name: "iPhone 12",
        brand: "Apple",
        desc: "5.4-inch mini display",
        price: 53000,
        image: "https://res.cloudinary.com/din4z2w7i/image/upload/v1711523674/online-shop/iphone12_mnusgn.jpg",
    },
    {
        id: 6,
        name: "Galaxy S",
        brand: "Samsung",
        desc: "6.5-inch display",
        price: 35000,
        image: "https://res.cloudinary.com/din4z2w7i/image/upload/v1711523674/online-shop/iphone12pro_k2kfnk.jpg",
    },
    {
        id: 7,
        name: "iPhone 12 Pro",
        brand: "Apple",
        desc: "6.1-inch display",
        price: 75000,
        image: "https://res.cloudinary.com/din4z2w7i/image/upload/v1711523674/online-shop/galaxyS_assruw.png",
    },
    {
        id: 8,
        name: "iPhone 12",
        brand: "Apple",
        desc: "5.4-inch mini display",
        price: 53000,
        image: "https://res.cloudinary.com/din4z2w7i/image/upload/v1711523674/online-shop/iphone12_mnusgn.jpg",
    },
    {
        id: 9,
        name: "Galaxy S",
        brand: "Samsung",
        desc: "6.5-inch display",
        price: 35000,
        image: "https://res.cloudinary.com/din4z2w7i/image/upload/v1711523674/online-shop/iphone12pro_k2kfnk.jpg",
    },
    {
        id: 10,
        name: "iPhone 12 Pro",
        brand: "Apple",
        desc: "6.1-inch display",
        price: 75000,
        image: "https://res.cloudinary.com/din4z2w7i/image/upload/v1711523674/online-shop/galaxyS_assruw.png",
    },
    {
        id: 11,
        name: "iPhone 12",
        brand: "Apple",
        desc: "5.4-inch mini display",
        price: 53000,
        image: "https://res.cloudinary.com/din4z2w7i/image/upload/v1711523674/online-shop/iphone12_mnusgn.jpg",
    },
    {
        id: 12,
        name: "Galaxy S",
        brand: "Samsung",
        desc: "6.5-inch display",
        price: 35000,
        image: "https://res.cloudinary.com/din4z2w7i/image/upload/v1711523674/online-shop/iphone12pro_k2kfnk.jpg",
    },
];

module.exports = products;